Tracker:AddLocations("locations/GoombaRegion.json")
Tracker:AddLocations("locations/ToadTown.json")
Tracker:AddLocations("locations/ToadTownTunnels.json")
Tracker:AddLocations("locations/PleasantPath.json")
Tracker:AddLocations("locations/DryDryDesert.json")
